image: maven:3.6.3-jdk-11-slim
stages:
  - build
  - test
  - release
  - deploy

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  SPRING_PROFILES_ACTIVE: ${CI_COMMIT_REF_NAME}

cache:
  paths:
    - $CI_PROJECT_DIR/.m2/repository

maven_build_job:
  stage: build
  only:
    changes:
      - hotel/**/*
  script:
    - mvn $MAVEN_CLI_OPTS clean install -DskipTests
  artifacts:
    when: on_success
    expire_in: 45 min
    paths:
      - hotel/target/*.jar

jfrog_deploy_job:
  stage: build
  only:
    refs:
      - master
    changes:
      - hotel/**/*
  before_script:
    # install Jfrog CLI
    - curl -fL https://getcli.jfrog.io | sh
    - ./jfrog rt c cloud-jfrog-artifactory --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_API_KEY
    - ./jfrog rt c show
  script:
    - ./jfrog rt mvn --settings ${MAVEN_SETTINGS_XML} clean install --build-name=gitlabci-hotel101-artifactory --build-number=$CI_JOB_ID
    - ./jfrog rt bce gitlabci-hotel101-artifactory $CI_JOB_ID
    - ./jfrog rt bp gitlabci-hotel101-artifactory $CI_JOB_ID

docker_build_job:
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOTEL_IMAGE: ${CI_REGISTRY_IMAGE}/hotel
    DOCKER_HOTEL_CONTEXT: hotel/Dockerfile
  stage: build
  image: docker:latest
  services:
    - name: docker:20.10.2-dind
  only:
    changes:
      - hotel/**/*
  before_script:
    - docker login -u ${GITLAB_USER_LOGIN} -p ${CI_TOKEN} ${CI_REGISTRY}
  script:
    - docker pull ${DOCKER_HOTEL_IMAGE}:latest || true
    - docker build
      --cache-from ${DOCKER_HOTEL_IMAGE}:latest
      --tag ${DOCKER_HOTEL_IMAGE}:latest
      --tag ${DOCKER_HOTEL_IMAGE}:${CI_COMMIT_SHORT_SHA} -f ${DOCKER_HOTEL_CONTEXT} .
    - docker push ${DOCKER_HOTEL_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker push ${DOCKER_HOTEL_IMAGE}:latest
  after_script:
    - docker logout ${CI_REGISTRY}

maven_test_job:
  stage: test
  only:
    changes:
      - hotel/**/*
  script:
    - mvn $MAVEN_CLI_OPTS verify -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}

maven_sonar_job:
  stage: test
  only:
    changes:
      - hotel/**/*
  script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=${SONAR_TOKEN} -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}

maven_release_job:
  stage: release
  before_script:
    - 'which git || (apt-get update && apt-get install -y git)'
    - git config --global user.name ${RELEASE_USER_NAME}
    - git config --global user.email ${RELEASE_USER_EMAIL}
  script:
    - git checkout -B ${CI_BUILD_REF_NAME}
    - mvn $MAVEN_CLI_OPTS -s ${MAVEN_SETTINGS_XML} release:clean release:prepare release:perform -DreleaseVersion=${RELEASE_VERSION} -DdevelopmentVersion=${NEXT_SNAPSHOT_VERSION}
  when: manual

ssh_deploy_qualification_job:
  stage: deploy
  image: kroniak/ssh-client
  tags:
    - qualification-deploy
  variables:
    DOCKER_HOTEL_IMAGE: ${CI_REGISTRY_IMAGE}/hotel
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa ${SSH_REMOTE_HOST} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh ${DEPLOY_USER}@${SSH_REMOTE_HOST} "docker login -u ${GITLAB_USER_LOGIN} -p ${CI_TOKEN} ${CI_REGISTRY}"
    - ssh ${DEPLOY_USER}@${SSH_REMOTE_HOST} "docker pull ${DOCKER_HOTEL_IMAGE}"
    - ssh ${DEPLOY_USER}@${SSH_REMOTE_HOST} "docker stop $(docker ps -aq)" || true
    - ssh ${DEPLOY_USER}@${SSH_REMOTE_HOST} "docker run  --rm -d -p 8080:8080 --name ${APP_NAME} --env-file .env ${DOCKER_HOTEL_IMAGE}"
  environment:
    name: qualification
    url: http://${SSH_REMOTE_HOST}
  only:
    refs:
      - qualification
    changes:
      - hotel/**/*

ssh_deploy_master_job:
  stage: deploy
  image: kroniak/ssh-client
  tags:
    - production-deploy
  variables:
    DOCKER_HOTEL_IMAGE: ${CI_REGISTRY_IMAGE}/hotel
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa ${SSH_REMOTE_HOST} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh ${DEPLOY_USER}@${SSH_REMOTE_HOST} "docker login -u ${GITLAB_USER_LOGIN} -p ${CI_TOKEN} ${CI_REGISTRY}"
    - ssh ${DEPLOY_USER}@${SSH_REMOTE_HOST} "docker pull ${DOCKER_HOTEL_IMAGE}"
    - ssh ${DEPLOY_USER}@${SSH_REMOTE_HOST} "docker stop $(docker ps -aq)" || true
    - ssh ${DEPLOY_USER}@${SSH_REMOTE_HOST} "docker run  --rm -d -p 8080:8080 --name ${APP_NAME} --env-file .env ${DOCKER_HOTEL_IMAGE}"
  environment:
    name: master
    url: http://${SSH_REMOTE_HOST}
  only:
    refs:
      - master
    changes:
      - hotel/**/*