spring:
  profiles: qualification
  data:
    mongodb:
      uri: mongodb://localhost:27017/hotels-${spring.profiles}
server:
  port: 8080
api:
  info:
    title: Hotel API
    version: 1.0.0
    description: Hotel API is web service providing online functionality of searching and booking hotels
  contact:
    email: mario-dacosta@hotmail.fr
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  uri:
    paths:
      hotel: /api/v1/hotels