# API HOTEL MANAGEMENT

### save()
POST {{host-url}}/hotels
Content-Type: application/json

{
  "name": "F1",
  "pricePerNight": 500,
  "reviews": [
    {
      "email": "mario-dacosta@hotmail.fr",
      "rating": 5
    }
  ],
  "address": {
    "city": "Paris",
    "country": "France"
  }
}

### getAll()
GET {{host-url}}//hotels

### update()
PUT {{host-url}}/hotels/600c6a07d73a547d0ccd2969
Content-Type: application/json

{
  "name": "F1",
  "pricePerNight": 1000,
  "reviews": [
    {
      "email": "mario-dacosta@hotmail.fr",
      "rating": 5
    },
    {
      "email": "semir-sator@hotmail.fr",
      "rating": 4
    }
  ],
  "address": {
    "city": "Paris",
    "country": "France"
  }
}

### delete()
DELETE {{host-url}}/hotels/600c6a07d73a547d0ccd2969

### getByHotelId()
GET {{host-url}}//hotels/5d986e236bb9813cc0a5149b

### filter()
GET {{host-url}}/hotels/price?min=100&max=1000