spring:
  profiles: master
  data:
    mongodb:
      uri: mongodb+srv://<username>:<password>@clustermongo01.xusit.mongodb.net/hotels-master?retryWrites=true&w=majority
      database: hotels-master
server:
  port: 8080
api:
  info:
    title: Hotel API
    version: 1.0.0
    description: Hotel API is a web service providing online hotel search and booking functionalities.
  contact:
    name: Mario DA COSTA
    url: https://github.com/Nakebenihime
    email: mario-dacosta@hotmail.fr
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  uri:
    paths:
      hotel: /api/v1/hotels