management:
  info:
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
spring:
  profiles: master
  data:
    mongodb:
      database: hotels-master
server:
  port: 8080
api:
  info:
    title: Hotel API
    version: 1.0.0
    description: Hotel API is a web service providing online hotel search and booking functionalities.
  contact:
    name: Mario DA COSTA
    url: https://github.com/Nakebenihime
    email: mario-dacosta@hotmail.fr
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  uri:
    paths:
      hotel: /api/v1/hotels
azure:
  keyvault:
    uri: ${AZURE_KEYVAULT_URI}
    client-id: ${AZURE_KEYVAULT_CLIENT_ID}
    client-key: ${AZURE_KEYVAULT_CLIENT_KEY}
    tenant-id: ${AZURE_KEYVAULT_TENANT_ID}
    enabled: true