spring:
  profiles: master
  data:
    mongodb:
      database: hotels-master
server:
  port: 8080
api:
  info:
    title: Hotel API
    version: 1.0.0
    description: Hotel API is a web service providing online hotel search and booking functionalities.
  contact:
    name: Mario DA COSTA
    url: https://github.com/Nakebenihime
    email: mario-dacosta@hotmail.fr
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  uri:
    paths:
      hotel: /api/v1/hotels
azure:
  keyvault:
    uri: https://springboot-app-key-vault.vault.azure.net/
    client-id: 547f8ce7-61a4-4853-8984-6569c8046235
    client-key: 691d-AQh2f9_P.qFFJLMKESivz0Tr0e1GC
    tenant-id: 9a201292-e579-4be6-a754-74a17631711a
    enabled: true